# Generated by Django 4.2 on 2023-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prddname', models.CharField(max_length=55)),
                ('prdimg', models.ImageField(upload_to='img_prd/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='img_def/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
