# Generated by Django 4.2 on 2023-05-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productimage_alter_product_img_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='media/img_def'),
        ),
    ]
