# Generated by Django 4.2 on 2023-05-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_productimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complet',
            new_name='complete',
        ),
    ]
